<?php
// Menu-Array zum Einfügen bzw. Löschen von neuen Seiten
$arrMenu = array(
	1=>array(
		'parent'=>0,
		'label'=>'Startseite',
		'template'=>'home',
		'file'=>'login',
		'name'=>'home',
	),
	2=>array(
		'parent'=>0,
		'label'=>'Registrieren',
		'template'=>'home',
		'file'=>'registration',
		'name'=>'registration',
	),
	3=>array(
		'parent'=>0,
		'label'=>'Eventerstellung',
		'template'=>'home',
		'file'=>'registration',
		'name'=>'eventerstellung',
	),
	4=>array(
		'parent'=>0,
		'label'=>'XY',
		'template'=>'home',
		'file'=>'test',
		'name'=>'xy',
	),
);
?>